def test_broken():
    raise ValueError('broken test')
